package com.example.thsmanager.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.thsmanager.entity.TorihikisakiMain;
import com.example.thsmanager.entity.TorihikisakiMainExample;

@Mapper
public interface TorihikisakiMainMapper {
	
	@Select("select * from sampledb.torihikisaki_main")
	List<TorihikisakiMain> selectTorihikisakiMains();
	
	@Select("select * from sampledb.torihikisaki_main where TORIHIKI_ID=#{torihikiId}")
	TorihikisakiMain selectTorihikisakiMain(Integer ID);
	
	@Insert("insert into sampledb.torihikisaki_main(TORIHIKI_NAME_ALL,TORIHIKI_RYAKU,YUUBIN,JYUSYO_1)values(#{torihikiNameAll},#{torihikiRyaku},#{yuubin},#{jyusyo1})")
	void addTorihikisakiMain(TorihikisakiMain torihikisakiMain);
	
	@Update("update sampledb.torihikisaki_main set TORIHIKI_NAME_ALL=#{torihikiNameALL},TORIHIKI_RYAKU=#{torihikiRyaku},YUUBIN=#{yuubin},JYUSYO_1=#{jyusyo1} where TORIHIKI_ID=#{torihikiId}")
	void updateTorihikisakiMain(TorihikisakiMain torihikisakiMain);
	
	@Delete("delete from sampledb.torihikisaki_main where TORIHIKI_ID=#{torihikiId}")
	void delTorihikisakiMain(Integer ID);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    long countByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int deleteByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int deleteByPrimaryKey(Integer torihikiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int insert(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int insertSelective(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    List<TorihikisakiMain> selectByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    TorihikisakiMain selectByPrimaryKey(Integer torihikiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int updateByExampleSelective(@Param("row") TorihikisakiMain row, @Param("example") TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int updateByExample(@Param("row") TorihikisakiMain row, @Param("example") TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int updateByPrimaryKeySelective(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Wed Dec 20 19:52:07 KST 2023
     */
    int updateByPrimaryKey(TorihikisakiMain row);
}