package com.example.thsmanager.entity;

import java.util.Date;

public class TorihikisakiMain {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.TORIHIKI_ID
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Long torihikiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.TORIHIKI_NAME_ALL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String torihikiNameAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.TORIHIKI_RYAKU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String torihikiRyaku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.YUUBIN
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String yuubin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.JYUSYO_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String jyusyo1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.JYUSYO_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String jyusyo2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.TEL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.FAX
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.URL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.BIKOU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String bikou;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.DELETE_FLAG
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_3
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_4
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_5
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_6
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer seikyusyouKubun6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_7
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String seikyusyouKubun7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_8
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String seikyusyouKubun8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_9
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String seikyusyouKubun9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_10
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String seikyusyouKubun10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SEIKYUSYOU_KUBUN_11
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String seikyusyouKubun11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.HONSYA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer honsya;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.HONSYA_KOUZA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer honsyaKouza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.KINYUKIKAN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String kinyukikanCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.KINYUKIKAN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String kinyukikanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SITEN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String sitenCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.SITEN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String sitenName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.KOUZA_KIND
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Integer kouzaKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.KOUZA_NUM
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String kouzaNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.MEIGI_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private String meigiName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.TOUROKUBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Date tourokubi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column torihikisaki_main.KOUSINBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	private Date kousinbi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.TORIHIKI_ID
	 * @return  the value of torihikisaki_main.TORIHIKI_ID
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Long getTorihikiId() {
		return torihikiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.TORIHIKI_ID
	 * @param torihikiId  the value for torihikisaki_main.TORIHIKI_ID
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setTorihikiId(Long torihikiId) {
		this.torihikiId = torihikiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.TORIHIKI_NAME_ALL
	 * @return  the value of torihikisaki_main.TORIHIKI_NAME_ALL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getTorihikiNameAll() {
		return torihikiNameAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.TORIHIKI_NAME_ALL
	 * @param torihikiNameAll  the value for torihikisaki_main.TORIHIKI_NAME_ALL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setTorihikiNameAll(String torihikiNameAll) {
		this.torihikiNameAll = torihikiNameAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.TORIHIKI_RYAKU
	 * @return  the value of torihikisaki_main.TORIHIKI_RYAKU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getTorihikiRyaku() {
		return torihikiRyaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.TORIHIKI_RYAKU
	 * @param torihikiRyaku  the value for torihikisaki_main.TORIHIKI_RYAKU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setTorihikiRyaku(String torihikiRyaku) {
		this.torihikiRyaku = torihikiRyaku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.YUUBIN
	 * @return  the value of torihikisaki_main.YUUBIN
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getYuubin() {
		return yuubin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.YUUBIN
	 * @param yuubin  the value for torihikisaki_main.YUUBIN
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setYuubin(String yuubin) {
		this.yuubin = yuubin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.JYUSYO_1
	 * @return  the value of torihikisaki_main.JYUSYO_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getJyusyo1() {
		return jyusyo1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.JYUSYO_1
	 * @param jyusyo1  the value for torihikisaki_main.JYUSYO_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setJyusyo1(String jyusyo1) {
		this.jyusyo1 = jyusyo1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.JYUSYO_2
	 * @return  the value of torihikisaki_main.JYUSYO_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getJyusyo2() {
		return jyusyo2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.JYUSYO_2
	 * @param jyusyo2  the value for torihikisaki_main.JYUSYO_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setJyusyo2(String jyusyo2) {
		this.jyusyo2 = jyusyo2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.TEL
	 * @return  the value of torihikisaki_main.TEL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.TEL
	 * @param tel  the value for torihikisaki_main.TEL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.FAX
	 * @return  the value of torihikisaki_main.FAX
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.FAX
	 * @param fax  the value for torihikisaki_main.FAX
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.URL
	 * @return  the value of torihikisaki_main.URL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.URL
	 * @param url  the value for torihikisaki_main.URL
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.BIKOU
	 * @return  the value of torihikisaki_main.BIKOU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getBikou() {
		return bikou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.BIKOU
	 * @param bikou  the value for torihikisaki_main.BIKOU
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setBikou(String bikou) {
		this.bikou = bikou;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.DELETE_FLAG
	 * @return  the value of torihikisaki_main.DELETE_FLAG
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.DELETE_FLAG
	 * @param deleteFlag  the value for torihikisaki_main.DELETE_FLAG
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_1
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun1() {
		return seikyusyouKubun1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_1
	 * @param seikyusyouKubun1  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_1
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun1(Integer seikyusyouKubun1) {
		this.seikyusyouKubun1 = seikyusyouKubun1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_2
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun2() {
		return seikyusyouKubun2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_2
	 * @param seikyusyouKubun2  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_2
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun2(Integer seikyusyouKubun2) {
		this.seikyusyouKubun2 = seikyusyouKubun2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_3
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_3
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun3() {
		return seikyusyouKubun3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_3
	 * @param seikyusyouKubun3  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_3
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun3(Integer seikyusyouKubun3) {
		this.seikyusyouKubun3 = seikyusyouKubun3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_4
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_4
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun4() {
		return seikyusyouKubun4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_4
	 * @param seikyusyouKubun4  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_4
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun4(Integer seikyusyouKubun4) {
		this.seikyusyouKubun4 = seikyusyouKubun4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_5
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_5
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun5() {
		return seikyusyouKubun5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_5
	 * @param seikyusyouKubun5  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_5
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun5(Integer seikyusyouKubun5) {
		this.seikyusyouKubun5 = seikyusyouKubun5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_6
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_6
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getSeikyusyouKubun6() {
		return seikyusyouKubun6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_6
	 * @param seikyusyouKubun6  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_6
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun6(Integer seikyusyouKubun6) {
		this.seikyusyouKubun6 = seikyusyouKubun6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_7
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_7
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSeikyusyouKubun7() {
		return seikyusyouKubun7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_7
	 * @param seikyusyouKubun7  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_7
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun7(String seikyusyouKubun7) {
		this.seikyusyouKubun7 = seikyusyouKubun7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_8
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_8
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSeikyusyouKubun8() {
		return seikyusyouKubun8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_8
	 * @param seikyusyouKubun8  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_8
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun8(String seikyusyouKubun8) {
		this.seikyusyouKubun8 = seikyusyouKubun8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_9
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_9
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSeikyusyouKubun9() {
		return seikyusyouKubun9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_9
	 * @param seikyusyouKubun9  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_9
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun9(String seikyusyouKubun9) {
		this.seikyusyouKubun9 = seikyusyouKubun9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_10
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_10
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSeikyusyouKubun10() {
		return seikyusyouKubun10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_10
	 * @param seikyusyouKubun10  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_10
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun10(String seikyusyouKubun10) {
		this.seikyusyouKubun10 = seikyusyouKubun10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_11
	 * @return  the value of torihikisaki_main.SEIKYUSYOU_KUBUN_11
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSeikyusyouKubun11() {
		return seikyusyouKubun11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SEIKYUSYOU_KUBUN_11
	 * @param seikyusyouKubun11  the value for torihikisaki_main.SEIKYUSYOU_KUBUN_11
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSeikyusyouKubun11(String seikyusyouKubun11) {
		this.seikyusyouKubun11 = seikyusyouKubun11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.HONSYA
	 * @return  the value of torihikisaki_main.HONSYA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getHonsya() {
		return honsya;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.HONSYA
	 * @param honsya  the value for torihikisaki_main.HONSYA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setHonsya(Integer honsya) {
		this.honsya = honsya;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.HONSYA_KOUZA
	 * @return  the value of torihikisaki_main.HONSYA_KOUZA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getHonsyaKouza() {
		return honsyaKouza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.HONSYA_KOUZA
	 * @param honsyaKouza  the value for torihikisaki_main.HONSYA_KOUZA
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setHonsyaKouza(Integer honsyaKouza) {
		this.honsyaKouza = honsyaKouza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.KINYUKIKAN_CODE
	 * @return  the value of torihikisaki_main.KINYUKIKAN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getKinyukikanCode() {
		return kinyukikanCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.KINYUKIKAN_CODE
	 * @param kinyukikanCode  the value for torihikisaki_main.KINYUKIKAN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setKinyukikanCode(String kinyukikanCode) {
		this.kinyukikanCode = kinyukikanCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.KINYUKIKAN_NAME
	 * @return  the value of torihikisaki_main.KINYUKIKAN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getKinyukikanName() {
		return kinyukikanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.KINYUKIKAN_NAME
	 * @param kinyukikanName  the value for torihikisaki_main.KINYUKIKAN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setKinyukikanName(String kinyukikanName) {
		this.kinyukikanName = kinyukikanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SITEN_CODE
	 * @return  the value of torihikisaki_main.SITEN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSitenCode() {
		return sitenCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SITEN_CODE
	 * @param sitenCode  the value for torihikisaki_main.SITEN_CODE
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSitenCode(String sitenCode) {
		this.sitenCode = sitenCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.SITEN_NAME
	 * @return  the value of torihikisaki_main.SITEN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getSitenName() {
		return sitenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.SITEN_NAME
	 * @param sitenName  the value for torihikisaki_main.SITEN_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setSitenName(String sitenName) {
		this.sitenName = sitenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.KOUZA_KIND
	 * @return  the value of torihikisaki_main.KOUZA_KIND
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Integer getKouzaKind() {
		return kouzaKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.KOUZA_KIND
	 * @param kouzaKind  the value for torihikisaki_main.KOUZA_KIND
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setKouzaKind(Integer kouzaKind) {
		this.kouzaKind = kouzaKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.KOUZA_NUM
	 * @return  the value of torihikisaki_main.KOUZA_NUM
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getKouzaNum() {
		return kouzaNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.KOUZA_NUM
	 * @param kouzaNum  the value for torihikisaki_main.KOUZA_NUM
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setKouzaNum(String kouzaNum) {
		this.kouzaNum = kouzaNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.MEIGI_NAME
	 * @return  the value of torihikisaki_main.MEIGI_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public String getMeigiName() {
		return meigiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.MEIGI_NAME
	 * @param meigiName  the value for torihikisaki_main.MEIGI_NAME
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setMeigiName(String meigiName) {
		this.meigiName = meigiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.TOUROKUBI
	 * @return  the value of torihikisaki_main.TOUROKUBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Date getTourokubi() {
		return tourokubi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.TOUROKUBI
	 * @param tourokubi  the value for torihikisaki_main.TOUROKUBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setTourokubi(Date tourokubi) {
		this.tourokubi = tourokubi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column torihikisaki_main.KOUSINBI
	 * @return  the value of torihikisaki_main.KOUSINBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public Date getKousinbi() {
		return kousinbi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column torihikisaki_main.KOUSINBI
	 * @param kousinbi  the value for torihikisaki_main.KOUSINBI
	 * @mbg.generated  Wed Dec 20 19:46:14 KST 2023
	 */
	public void setKousinbi(Date kousinbi) {
		this.kousinbi = kousinbi;
	}
}