package com.example.thsmanager.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TorihikisakiMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public TorihikisakiMainExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTorihikiIdIsNull() {
            addCriterion("TORIHIKI_ID is null");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdIsNotNull() {
            addCriterion("TORIHIKI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdEqualTo(Long value) {
            addCriterion("TORIHIKI_ID =", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotEqualTo(Long value) {
            addCriterion("TORIHIKI_ID <>", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdGreaterThan(Long value) {
            addCriterion("TORIHIKI_ID >", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TORIHIKI_ID >=", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdLessThan(Long value) {
            addCriterion("TORIHIKI_ID <", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdLessThanOrEqualTo(Long value) {
            addCriterion("TORIHIKI_ID <=", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdIn(List<Long> values) {
            addCriterion("TORIHIKI_ID in", values, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotIn(List<Long> values) {
            addCriterion("TORIHIKI_ID not in", values, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdBetween(Long value1, Long value2) {
            addCriterion("TORIHIKI_ID between", value1, value2, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotBetween(Long value1, Long value2) {
            addCriterion("TORIHIKI_ID not between", value1, value2, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllIsNull() {
            addCriterion("TORIHIKI_NAME_ALL is null");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllIsNotNull() {
            addCriterion("TORIHIKI_NAME_ALL is not null");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllEqualTo(String value) {
            addCriterion("TORIHIKI_NAME_ALL =", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllNotEqualTo(String value) {
            addCriterion("TORIHIKI_NAME_ALL <>", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllGreaterThan(String value) {
            addCriterion("TORIHIKI_NAME_ALL >", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllGreaterThanOrEqualTo(String value) {
            addCriterion("TORIHIKI_NAME_ALL >=", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllLessThan(String value) {
            addCriterion("TORIHIKI_NAME_ALL <", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllLessThanOrEqualTo(String value) {
            addCriterion("TORIHIKI_NAME_ALL <=", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllLike(String value) {
            addCriterion("TORIHIKI_NAME_ALL like", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllNotLike(String value) {
            addCriterion("TORIHIKI_NAME_ALL not like", value, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllIn(List<String> values) {
            addCriterion("TORIHIKI_NAME_ALL in", values, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllNotIn(List<String> values) {
            addCriterion("TORIHIKI_NAME_ALL not in", values, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllBetween(String value1, String value2) {
            addCriterion("TORIHIKI_NAME_ALL between", value1, value2, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiNameAllNotBetween(String value1, String value2) {
            addCriterion("TORIHIKI_NAME_ALL not between", value1, value2, "torihikiNameAll");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuIsNull() {
            addCriterion("TORIHIKI_RYAKU is null");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuIsNotNull() {
            addCriterion("TORIHIKI_RYAKU is not null");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuEqualTo(String value) {
            addCriterion("TORIHIKI_RYAKU =", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuNotEqualTo(String value) {
            addCriterion("TORIHIKI_RYAKU <>", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuGreaterThan(String value) {
            addCriterion("TORIHIKI_RYAKU >", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuGreaterThanOrEqualTo(String value) {
            addCriterion("TORIHIKI_RYAKU >=", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuLessThan(String value) {
            addCriterion("TORIHIKI_RYAKU <", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuLessThanOrEqualTo(String value) {
            addCriterion("TORIHIKI_RYAKU <=", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuLike(String value) {
            addCriterion("TORIHIKI_RYAKU like", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuNotLike(String value) {
            addCriterion("TORIHIKI_RYAKU not like", value, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuIn(List<String> values) {
            addCriterion("TORIHIKI_RYAKU in", values, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuNotIn(List<String> values) {
            addCriterion("TORIHIKI_RYAKU not in", values, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuBetween(String value1, String value2) {
            addCriterion("TORIHIKI_RYAKU between", value1, value2, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andTorihikiRyakuNotBetween(String value1, String value2) {
            addCriterion("TORIHIKI_RYAKU not between", value1, value2, "torihikiRyaku");
            return (Criteria) this;
        }

        public Criteria andYuubinIsNull() {
            addCriterion("YUUBIN is null");
            return (Criteria) this;
        }

        public Criteria andYuubinIsNotNull() {
            addCriterion("YUUBIN is not null");
            return (Criteria) this;
        }

        public Criteria andYuubinEqualTo(String value) {
            addCriterion("YUUBIN =", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinNotEqualTo(String value) {
            addCriterion("YUUBIN <>", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinGreaterThan(String value) {
            addCriterion("YUUBIN >", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinGreaterThanOrEqualTo(String value) {
            addCriterion("YUUBIN >=", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinLessThan(String value) {
            addCriterion("YUUBIN <", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinLessThanOrEqualTo(String value) {
            addCriterion("YUUBIN <=", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinLike(String value) {
            addCriterion("YUUBIN like", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinNotLike(String value) {
            addCriterion("YUUBIN not like", value, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinIn(List<String> values) {
            addCriterion("YUUBIN in", values, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinNotIn(List<String> values) {
            addCriterion("YUUBIN not in", values, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinBetween(String value1, String value2) {
            addCriterion("YUUBIN between", value1, value2, "yuubin");
            return (Criteria) this;
        }

        public Criteria andYuubinNotBetween(String value1, String value2) {
            addCriterion("YUUBIN not between", value1, value2, "yuubin");
            return (Criteria) this;
        }

        public Criteria andJyusyo1IsNull() {
            addCriterion("JYUSYO_1 is null");
            return (Criteria) this;
        }

        public Criteria andJyusyo1IsNotNull() {
            addCriterion("JYUSYO_1 is not null");
            return (Criteria) this;
        }

        public Criteria andJyusyo1EqualTo(String value) {
            addCriterion("JYUSYO_1 =", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1NotEqualTo(String value) {
            addCriterion("JYUSYO_1 <>", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1GreaterThan(String value) {
            addCriterion("JYUSYO_1 >", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1GreaterThanOrEqualTo(String value) {
            addCriterion("JYUSYO_1 >=", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1LessThan(String value) {
            addCriterion("JYUSYO_1 <", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1LessThanOrEqualTo(String value) {
            addCriterion("JYUSYO_1 <=", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1Like(String value) {
            addCriterion("JYUSYO_1 like", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1NotLike(String value) {
            addCriterion("JYUSYO_1 not like", value, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1In(List<String> values) {
            addCriterion("JYUSYO_1 in", values, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1NotIn(List<String> values) {
            addCriterion("JYUSYO_1 not in", values, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1Between(String value1, String value2) {
            addCriterion("JYUSYO_1 between", value1, value2, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo1NotBetween(String value1, String value2) {
            addCriterion("JYUSYO_1 not between", value1, value2, "jyusyo1");
            return (Criteria) this;
        }

        public Criteria andJyusyo2IsNull() {
            addCriterion("JYUSYO_2 is null");
            return (Criteria) this;
        }

        public Criteria andJyusyo2IsNotNull() {
            addCriterion("JYUSYO_2 is not null");
            return (Criteria) this;
        }

        public Criteria andJyusyo2EqualTo(String value) {
            addCriterion("JYUSYO_2 =", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2NotEqualTo(String value) {
            addCriterion("JYUSYO_2 <>", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2GreaterThan(String value) {
            addCriterion("JYUSYO_2 >", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2GreaterThanOrEqualTo(String value) {
            addCriterion("JYUSYO_2 >=", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2LessThan(String value) {
            addCriterion("JYUSYO_2 <", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2LessThanOrEqualTo(String value) {
            addCriterion("JYUSYO_2 <=", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2Like(String value) {
            addCriterion("JYUSYO_2 like", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2NotLike(String value) {
            addCriterion("JYUSYO_2 not like", value, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2In(List<String> values) {
            addCriterion("JYUSYO_2 in", values, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2NotIn(List<String> values) {
            addCriterion("JYUSYO_2 not in", values, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2Between(String value1, String value2) {
            addCriterion("JYUSYO_2 between", value1, value2, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andJyusyo2NotBetween(String value1, String value2) {
            addCriterion("JYUSYO_2 not between", value1, value2, "jyusyo2");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("FAX =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("FAX <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("FAX >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("FAX <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("FAX like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("FAX not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("FAX in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("FAX not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andBikouIsNull() {
            addCriterion("BIKOU is null");
            return (Criteria) this;
        }

        public Criteria andBikouIsNotNull() {
            addCriterion("BIKOU is not null");
            return (Criteria) this;
        }

        public Criteria andBikouEqualTo(String value) {
            addCriterion("BIKOU =", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotEqualTo(String value) {
            addCriterion("BIKOU <>", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouGreaterThan(String value) {
            addCriterion("BIKOU >", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouGreaterThanOrEqualTo(String value) {
            addCriterion("BIKOU >=", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLessThan(String value) {
            addCriterion("BIKOU <", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLessThanOrEqualTo(String value) {
            addCriterion("BIKOU <=", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLike(String value) {
            addCriterion("BIKOU like", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotLike(String value) {
            addCriterion("BIKOU not like", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouIn(List<String> values) {
            addCriterion("BIKOU in", values, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotIn(List<String> values) {
            addCriterion("BIKOU not in", values, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouBetween(String value1, String value2) {
            addCriterion("BIKOU between", value1, value2, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotBetween(String value1, String value2) {
            addCriterion("BIKOU not between", value1, value2, "bikou");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_1 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_1 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 =", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 <>", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 >", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 >=", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 <", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_1 <=", value, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_1 in", values, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_1 not in", values, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_1 between", value1, value2, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun1NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_1 not between", value1, value2, "seikyusyouKubun1");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_2 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_2 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 =", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 <>", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 >", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 >=", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 <", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_2 <=", value, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_2 in", values, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_2 not in", values, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_2 between", value1, value2, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun2NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_2 not between", value1, value2, "seikyusyouKubun2");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_3 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_3 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 =", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 <>", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 >", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 >=", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 <", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_3 <=", value, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_3 in", values, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_3 not in", values, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_3 between", value1, value2, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun3NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_3 not between", value1, value2, "seikyusyouKubun3");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_4 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_4 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 =", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 <>", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 >", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 >=", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 <", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_4 <=", value, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_4 in", values, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_4 not in", values, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_4 between", value1, value2, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun4NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_4 not between", value1, value2, "seikyusyouKubun4");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_5 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_5 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 =", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 <>", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 >", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 >=", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 <", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_5 <=", value, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_5 in", values, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_5 not in", values, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_5 between", value1, value2, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun5NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_5 not between", value1, value2, "seikyusyouKubun5");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_6 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_6 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6EqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 =", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6NotEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 <>", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6GreaterThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 >", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6GreaterThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 >=", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6LessThan(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 <", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6LessThanOrEqualTo(Integer value) {
            addCriterion("SEIKYUSYOU_KUBUN_6 <=", value, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6In(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_6 in", values, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6NotIn(List<Integer> values) {
            addCriterion("SEIKYUSYOU_KUBUN_6 not in", values, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6Between(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_6 between", value1, value2, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun6NotBetween(Integer value1, Integer value2) {
            addCriterion("SEIKYUSYOU_KUBUN_6 not between", value1, value2, "seikyusyouKubun6");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_7 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_7 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7EqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 =", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7NotEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 <>", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7GreaterThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 >", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7GreaterThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 >=", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7LessThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 <", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7LessThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 <=", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7Like(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 like", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7NotLike(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_7 not like", value, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7In(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_7 in", values, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7NotIn(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_7 not in", values, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7Between(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_7 between", value1, value2, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun7NotBetween(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_7 not between", value1, value2, "seikyusyouKubun7");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_8 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_8 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8EqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 =", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8NotEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 <>", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8GreaterThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 >", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8GreaterThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 >=", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8LessThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 <", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8LessThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 <=", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8Like(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 like", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8NotLike(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_8 not like", value, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8In(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_8 in", values, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8NotIn(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_8 not in", values, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8Between(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_8 between", value1, value2, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun8NotBetween(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_8 not between", value1, value2, "seikyusyouKubun8");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_9 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_9 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9EqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 =", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9NotEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 <>", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9GreaterThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 >", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9GreaterThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 >=", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9LessThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 <", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9LessThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 <=", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9Like(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 like", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9NotLike(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_9 not like", value, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9In(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_9 in", values, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9NotIn(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_9 not in", values, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9Between(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_9 between", value1, value2, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun9NotBetween(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_9 not between", value1, value2, "seikyusyouKubun9");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_10 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_10 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10EqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 =", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10NotEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 <>", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10GreaterThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 >", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10GreaterThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 >=", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10LessThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 <", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10LessThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 <=", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10Like(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 like", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10NotLike(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_10 not like", value, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10In(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_10 in", values, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10NotIn(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_10 not in", values, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10Between(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_10 between", value1, value2, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun10NotBetween(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_10 not between", value1, value2, "seikyusyouKubun10");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11IsNull() {
            addCriterion("SEIKYUSYOU_KUBUN_11 is null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11IsNotNull() {
            addCriterion("SEIKYUSYOU_KUBUN_11 is not null");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11EqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 =", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11NotEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 <>", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11GreaterThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 >", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11GreaterThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 >=", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11LessThan(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 <", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11LessThanOrEqualTo(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 <=", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11Like(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 like", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11NotLike(String value) {
            addCriterion("SEIKYUSYOU_KUBUN_11 not like", value, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11In(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_11 in", values, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11NotIn(List<String> values) {
            addCriterion("SEIKYUSYOU_KUBUN_11 not in", values, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11Between(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_11 between", value1, value2, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andSeikyusyouKubun11NotBetween(String value1, String value2) {
            addCriterion("SEIKYUSYOU_KUBUN_11 not between", value1, value2, "seikyusyouKubun11");
            return (Criteria) this;
        }

        public Criteria andHonsyaIsNull() {
            addCriterion("HONSYA is null");
            return (Criteria) this;
        }

        public Criteria andHonsyaIsNotNull() {
            addCriterion("HONSYA is not null");
            return (Criteria) this;
        }

        public Criteria andHonsyaEqualTo(Integer value) {
            addCriterion("HONSYA =", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaNotEqualTo(Integer value) {
            addCriterion("HONSYA <>", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaGreaterThan(Integer value) {
            addCriterion("HONSYA >", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaGreaterThanOrEqualTo(Integer value) {
            addCriterion("HONSYA >=", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaLessThan(Integer value) {
            addCriterion("HONSYA <", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaLessThanOrEqualTo(Integer value) {
            addCriterion("HONSYA <=", value, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaIn(List<Integer> values) {
            addCriterion("HONSYA in", values, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaNotIn(List<Integer> values) {
            addCriterion("HONSYA not in", values, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaBetween(Integer value1, Integer value2) {
            addCriterion("HONSYA between", value1, value2, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaNotBetween(Integer value1, Integer value2) {
            addCriterion("HONSYA not between", value1, value2, "honsya");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaIsNull() {
            addCriterion("HONSYA_KOUZA is null");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaIsNotNull() {
            addCriterion("HONSYA_KOUZA is not null");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaEqualTo(Integer value) {
            addCriterion("HONSYA_KOUZA =", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaNotEqualTo(Integer value) {
            addCriterion("HONSYA_KOUZA <>", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaGreaterThan(Integer value) {
            addCriterion("HONSYA_KOUZA >", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaGreaterThanOrEqualTo(Integer value) {
            addCriterion("HONSYA_KOUZA >=", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaLessThan(Integer value) {
            addCriterion("HONSYA_KOUZA <", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaLessThanOrEqualTo(Integer value) {
            addCriterion("HONSYA_KOUZA <=", value, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaIn(List<Integer> values) {
            addCriterion("HONSYA_KOUZA in", values, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaNotIn(List<Integer> values) {
            addCriterion("HONSYA_KOUZA not in", values, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaBetween(Integer value1, Integer value2) {
            addCriterion("HONSYA_KOUZA between", value1, value2, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andHonsyaKouzaNotBetween(Integer value1, Integer value2) {
            addCriterion("HONSYA_KOUZA not between", value1, value2, "honsyaKouza");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeIsNull() {
            addCriterion("KINYUKIKAN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeIsNotNull() {
            addCriterion("KINYUKIKAN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeEqualTo(String value) {
            addCriterion("KINYUKIKAN_CODE =", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeNotEqualTo(String value) {
            addCriterion("KINYUKIKAN_CODE <>", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeGreaterThan(String value) {
            addCriterion("KINYUKIKAN_CODE >", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeGreaterThanOrEqualTo(String value) {
            addCriterion("KINYUKIKAN_CODE >=", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeLessThan(String value) {
            addCriterion("KINYUKIKAN_CODE <", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeLessThanOrEqualTo(String value) {
            addCriterion("KINYUKIKAN_CODE <=", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeLike(String value) {
            addCriterion("KINYUKIKAN_CODE like", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeNotLike(String value) {
            addCriterion("KINYUKIKAN_CODE not like", value, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeIn(List<String> values) {
            addCriterion("KINYUKIKAN_CODE in", values, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeNotIn(List<String> values) {
            addCriterion("KINYUKIKAN_CODE not in", values, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeBetween(String value1, String value2) {
            addCriterion("KINYUKIKAN_CODE between", value1, value2, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanCodeNotBetween(String value1, String value2) {
            addCriterion("KINYUKIKAN_CODE not between", value1, value2, "kinyukikanCode");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameIsNull() {
            addCriterion("KINYUKIKAN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameIsNotNull() {
            addCriterion("KINYUKIKAN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameEqualTo(String value) {
            addCriterion("KINYUKIKAN_NAME =", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameNotEqualTo(String value) {
            addCriterion("KINYUKIKAN_NAME <>", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameGreaterThan(String value) {
            addCriterion("KINYUKIKAN_NAME >", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameGreaterThanOrEqualTo(String value) {
            addCriterion("KINYUKIKAN_NAME >=", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameLessThan(String value) {
            addCriterion("KINYUKIKAN_NAME <", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameLessThanOrEqualTo(String value) {
            addCriterion("KINYUKIKAN_NAME <=", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameLike(String value) {
            addCriterion("KINYUKIKAN_NAME like", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameNotLike(String value) {
            addCriterion("KINYUKIKAN_NAME not like", value, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameIn(List<String> values) {
            addCriterion("KINYUKIKAN_NAME in", values, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameNotIn(List<String> values) {
            addCriterion("KINYUKIKAN_NAME not in", values, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameBetween(String value1, String value2) {
            addCriterion("KINYUKIKAN_NAME between", value1, value2, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andKinyukikanNameNotBetween(String value1, String value2) {
            addCriterion("KINYUKIKAN_NAME not between", value1, value2, "kinyukikanName");
            return (Criteria) this;
        }

        public Criteria andSitenCodeIsNull() {
            addCriterion("SITEN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSitenCodeIsNotNull() {
            addCriterion("SITEN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSitenCodeEqualTo(String value) {
            addCriterion("SITEN_CODE =", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeNotEqualTo(String value) {
            addCriterion("SITEN_CODE <>", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeGreaterThan(String value) {
            addCriterion("SITEN_CODE >", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SITEN_CODE >=", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeLessThan(String value) {
            addCriterion("SITEN_CODE <", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeLessThanOrEqualTo(String value) {
            addCriterion("SITEN_CODE <=", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeLike(String value) {
            addCriterion("SITEN_CODE like", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeNotLike(String value) {
            addCriterion("SITEN_CODE not like", value, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeIn(List<String> values) {
            addCriterion("SITEN_CODE in", values, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeNotIn(List<String> values) {
            addCriterion("SITEN_CODE not in", values, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeBetween(String value1, String value2) {
            addCriterion("SITEN_CODE between", value1, value2, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenCodeNotBetween(String value1, String value2) {
            addCriterion("SITEN_CODE not between", value1, value2, "sitenCode");
            return (Criteria) this;
        }

        public Criteria andSitenNameIsNull() {
            addCriterion("SITEN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSitenNameIsNotNull() {
            addCriterion("SITEN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSitenNameEqualTo(String value) {
            addCriterion("SITEN_NAME =", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameNotEqualTo(String value) {
            addCriterion("SITEN_NAME <>", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameGreaterThan(String value) {
            addCriterion("SITEN_NAME >", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameGreaterThanOrEqualTo(String value) {
            addCriterion("SITEN_NAME >=", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameLessThan(String value) {
            addCriterion("SITEN_NAME <", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameLessThanOrEqualTo(String value) {
            addCriterion("SITEN_NAME <=", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameLike(String value) {
            addCriterion("SITEN_NAME like", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameNotLike(String value) {
            addCriterion("SITEN_NAME not like", value, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameIn(List<String> values) {
            addCriterion("SITEN_NAME in", values, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameNotIn(List<String> values) {
            addCriterion("SITEN_NAME not in", values, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameBetween(String value1, String value2) {
            addCriterion("SITEN_NAME between", value1, value2, "sitenName");
            return (Criteria) this;
        }

        public Criteria andSitenNameNotBetween(String value1, String value2) {
            addCriterion("SITEN_NAME not between", value1, value2, "sitenName");
            return (Criteria) this;
        }

        public Criteria andKouzaKindIsNull() {
            addCriterion("KOUZA_KIND is null");
            return (Criteria) this;
        }

        public Criteria andKouzaKindIsNotNull() {
            addCriterion("KOUZA_KIND is not null");
            return (Criteria) this;
        }

        public Criteria andKouzaKindEqualTo(Integer value) {
            addCriterion("KOUZA_KIND =", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindNotEqualTo(Integer value) {
            addCriterion("KOUZA_KIND <>", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindGreaterThan(Integer value) {
            addCriterion("KOUZA_KIND >", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("KOUZA_KIND >=", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindLessThan(Integer value) {
            addCriterion("KOUZA_KIND <", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindLessThanOrEqualTo(Integer value) {
            addCriterion("KOUZA_KIND <=", value, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindIn(List<Integer> values) {
            addCriterion("KOUZA_KIND in", values, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindNotIn(List<Integer> values) {
            addCriterion("KOUZA_KIND not in", values, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindBetween(Integer value1, Integer value2) {
            addCriterion("KOUZA_KIND between", value1, value2, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaKindNotBetween(Integer value1, Integer value2) {
            addCriterion("KOUZA_KIND not between", value1, value2, "kouzaKind");
            return (Criteria) this;
        }

        public Criteria andKouzaNumIsNull() {
            addCriterion("KOUZA_NUM is null");
            return (Criteria) this;
        }

        public Criteria andKouzaNumIsNotNull() {
            addCriterion("KOUZA_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andKouzaNumEqualTo(String value) {
            addCriterion("KOUZA_NUM =", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumNotEqualTo(String value) {
            addCriterion("KOUZA_NUM <>", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumGreaterThan(String value) {
            addCriterion("KOUZA_NUM >", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumGreaterThanOrEqualTo(String value) {
            addCriterion("KOUZA_NUM >=", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumLessThan(String value) {
            addCriterion("KOUZA_NUM <", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumLessThanOrEqualTo(String value) {
            addCriterion("KOUZA_NUM <=", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumLike(String value) {
            addCriterion("KOUZA_NUM like", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumNotLike(String value) {
            addCriterion("KOUZA_NUM not like", value, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumIn(List<String> values) {
            addCriterion("KOUZA_NUM in", values, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumNotIn(List<String> values) {
            addCriterion("KOUZA_NUM not in", values, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumBetween(String value1, String value2) {
            addCriterion("KOUZA_NUM between", value1, value2, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andKouzaNumNotBetween(String value1, String value2) {
            addCriterion("KOUZA_NUM not between", value1, value2, "kouzaNum");
            return (Criteria) this;
        }

        public Criteria andMeigiNameIsNull() {
            addCriterion("MEIGI_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMeigiNameIsNotNull() {
            addCriterion("MEIGI_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMeigiNameEqualTo(String value) {
            addCriterion("MEIGI_NAME =", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameNotEqualTo(String value) {
            addCriterion("MEIGI_NAME <>", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameGreaterThan(String value) {
            addCriterion("MEIGI_NAME >", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameGreaterThanOrEqualTo(String value) {
            addCriterion("MEIGI_NAME >=", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameLessThan(String value) {
            addCriterion("MEIGI_NAME <", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameLessThanOrEqualTo(String value) {
            addCriterion("MEIGI_NAME <=", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameLike(String value) {
            addCriterion("MEIGI_NAME like", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameNotLike(String value) {
            addCriterion("MEIGI_NAME not like", value, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameIn(List<String> values) {
            addCriterion("MEIGI_NAME in", values, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameNotIn(List<String> values) {
            addCriterion("MEIGI_NAME not in", values, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameBetween(String value1, String value2) {
            addCriterion("MEIGI_NAME between", value1, value2, "meigiName");
            return (Criteria) this;
        }

        public Criteria andMeigiNameNotBetween(String value1, String value2) {
            addCriterion("MEIGI_NAME not between", value1, value2, "meigiName");
            return (Criteria) this;
        }

        public Criteria andTourokubiIsNull() {
            addCriterion("TOUROKUBI is null");
            return (Criteria) this;
        }

        public Criteria andTourokubiIsNotNull() {
            addCriterion("TOUROKUBI is not null");
            return (Criteria) this;
        }

        public Criteria andTourokubiEqualTo(Date value) {
            addCriterion("TOUROKUBI =", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotEqualTo(Date value) {
            addCriterion("TOUROKUBI <>", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiGreaterThan(Date value) {
            addCriterion("TOUROKUBI >", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiGreaterThanOrEqualTo(Date value) {
            addCriterion("TOUROKUBI >=", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiLessThan(Date value) {
            addCriterion("TOUROKUBI <", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiLessThanOrEqualTo(Date value) {
            addCriterion("TOUROKUBI <=", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiIn(List<Date> values) {
            addCriterion("TOUROKUBI in", values, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotIn(List<Date> values) {
            addCriterion("TOUROKUBI not in", values, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiBetween(Date value1, Date value2) {
            addCriterion("TOUROKUBI between", value1, value2, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotBetween(Date value1, Date value2) {
            addCriterion("TOUROKUBI not between", value1, value2, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andKousinbiIsNull() {
            addCriterion("KOUSINBI is null");
            return (Criteria) this;
        }

        public Criteria andKousinbiIsNotNull() {
            addCriterion("KOUSINBI is not null");
            return (Criteria) this;
        }

        public Criteria andKousinbiEqualTo(Date value) {
            addCriterion("KOUSINBI =", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotEqualTo(Date value) {
            addCriterion("KOUSINBI <>", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiGreaterThan(Date value) {
            addCriterion("KOUSINBI >", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiGreaterThanOrEqualTo(Date value) {
            addCriterion("KOUSINBI >=", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiLessThan(Date value) {
            addCriterion("KOUSINBI <", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiLessThanOrEqualTo(Date value) {
            addCriterion("KOUSINBI <=", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiIn(List<Date> values) {
            addCriterion("KOUSINBI in", values, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotIn(List<Date> values) {
            addCriterion("KOUSINBI not in", values, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiBetween(Date value1, Date value2) {
            addCriterion("KOUSINBI between", value1, value2, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotBetween(Date value1, Date value2) {
            addCriterion("KOUSINBI not between", value1, value2, "kousinbi");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_main
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 18 16:49:45 KST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Mon Dec 18 16:49:45 KST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}