package com.example.thsmanager.entity;

import java.util.ArrayList;
import java.util.List;

public class TorihikisakiTantouExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public TorihikisakiTantouExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTantouIdIsNull() {
            addCriterion("TANTOU_ID is null");
            return (Criteria) this;
        }

        public Criteria andTantouIdIsNotNull() {
            addCriterion("TANTOU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTantouIdEqualTo(Integer value) {
            addCriterion("TANTOU_ID =", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdNotEqualTo(Integer value) {
            addCriterion("TANTOU_ID <>", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdGreaterThan(Integer value) {
            addCriterion("TANTOU_ID >", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TANTOU_ID >=", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdLessThan(Integer value) {
            addCriterion("TANTOU_ID <", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdLessThanOrEqualTo(Integer value) {
            addCriterion("TANTOU_ID <=", value, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdIn(List<Integer> values) {
            addCriterion("TANTOU_ID in", values, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdNotIn(List<Integer> values) {
            addCriterion("TANTOU_ID not in", values, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdBetween(Integer value1, Integer value2) {
            addCriterion("TANTOU_ID between", value1, value2, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTantouIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TANTOU_ID not between", value1, value2, "tantouId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdIsNull() {
            addCriterion("TORIHIKI_ID is null");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdIsNotNull() {
            addCriterion("TORIHIKI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdEqualTo(Integer value) {
            addCriterion("TORIHIKI_ID =", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotEqualTo(Integer value) {
            addCriterion("TORIHIKI_ID <>", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdGreaterThan(Integer value) {
            addCriterion("TORIHIKI_ID >", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TORIHIKI_ID >=", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdLessThan(Integer value) {
            addCriterion("TORIHIKI_ID <", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdLessThanOrEqualTo(Integer value) {
            addCriterion("TORIHIKI_ID <=", value, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdIn(List<Integer> values) {
            addCriterion("TORIHIKI_ID in", values, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotIn(List<Integer> values) {
            addCriterion("TORIHIKI_ID not in", values, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdBetween(Integer value1, Integer value2) {
            addCriterion("TORIHIKI_ID between", value1, value2, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andTorihikiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TORIHIKI_ID not between", value1, value2, "torihikiId");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNull() {
            addCriterion("FIRST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNotNull() {
            addCriterion("FIRST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFirstNameEqualTo(String value) {
            addCriterion("FIRST_NAME =", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotEqualTo(String value) {
            addCriterion("FIRST_NAME <>", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThan(String value) {
            addCriterion("FIRST_NAME >", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME >=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThan(String value) {
            addCriterion("FIRST_NAME <", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME <=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLike(String value) {
            addCriterion("FIRST_NAME like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotLike(String value) {
            addCriterion("FIRST_NAME not like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameIn(List<String> values) {
            addCriterion("FIRST_NAME in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotIn(List<String> values) {
            addCriterion("FIRST_NAME not in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameBetween(String value1, String value2) {
            addCriterion("FIRST_NAME between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotBetween(String value1, String value2) {
            addCriterion("FIRST_NAME not between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNull() {
            addCriterion("LAST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNotNull() {
            addCriterion("LAST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLastNameEqualTo(String value) {
            addCriterion("LAST_NAME =", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotEqualTo(String value) {
            addCriterion("LAST_NAME <>", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThan(String value) {
            addCriterion("LAST_NAME >", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_NAME >=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThan(String value) {
            addCriterion("LAST_NAME <", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThanOrEqualTo(String value) {
            addCriterion("LAST_NAME <=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLike(String value) {
            addCriterion("LAST_NAME like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotLike(String value) {
            addCriterion("LAST_NAME not like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameIn(List<String> values) {
            addCriterion("LAST_NAME in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotIn(List<String> values) {
            addCriterion("LAST_NAME not in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameBetween(String value1, String value2) {
            addCriterion("LAST_NAME between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotBetween(String value1, String value2) {
            addCriterion("LAST_NAME not between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andSyozokuIsNull() {
            addCriterion("SYOZOKU is null");
            return (Criteria) this;
        }

        public Criteria andSyozokuIsNotNull() {
            addCriterion("SYOZOKU is not null");
            return (Criteria) this;
        }

        public Criteria andSyozokuEqualTo(String value) {
            addCriterion("SYOZOKU =", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuNotEqualTo(String value) {
            addCriterion("SYOZOKU <>", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuGreaterThan(String value) {
            addCriterion("SYOZOKU >", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuGreaterThanOrEqualTo(String value) {
            addCriterion("SYOZOKU >=", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuLessThan(String value) {
            addCriterion("SYOZOKU <", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuLessThanOrEqualTo(String value) {
            addCriterion("SYOZOKU <=", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuLike(String value) {
            addCriterion("SYOZOKU like", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuNotLike(String value) {
            addCriterion("SYOZOKU not like", value, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuIn(List<String> values) {
            addCriterion("SYOZOKU in", values, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuNotIn(List<String> values) {
            addCriterion("SYOZOKU not in", values, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuBetween(String value1, String value2) {
            addCriterion("SYOZOKU between", value1, value2, "syozoku");
            return (Criteria) this;
        }

        public Criteria andSyozokuNotBetween(String value1, String value2) {
            addCriterion("SYOZOKU not between", value1, value2, "syozoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuIsNull() {
            addCriterion("YAKUSYOKU is null");
            return (Criteria) this;
        }

        public Criteria andYakusyokuIsNotNull() {
            addCriterion("YAKUSYOKU is not null");
            return (Criteria) this;
        }

        public Criteria andYakusyokuEqualTo(String value) {
            addCriterion("YAKUSYOKU =", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuNotEqualTo(String value) {
            addCriterion("YAKUSYOKU <>", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuGreaterThan(String value) {
            addCriterion("YAKUSYOKU >", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuGreaterThanOrEqualTo(String value) {
            addCriterion("YAKUSYOKU >=", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuLessThan(String value) {
            addCriterion("YAKUSYOKU <", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuLessThanOrEqualTo(String value) {
            addCriterion("YAKUSYOKU <=", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuLike(String value) {
            addCriterion("YAKUSYOKU like", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuNotLike(String value) {
            addCriterion("YAKUSYOKU not like", value, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuIn(List<String> values) {
            addCriterion("YAKUSYOKU in", values, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuNotIn(List<String> values) {
            addCriterion("YAKUSYOKU not in", values, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuBetween(String value1, String value2) {
            addCriterion("YAKUSYOKU between", value1, value2, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andYakusyokuNotBetween(String value1, String value2) {
            addCriterion("YAKUSYOKU not between", value1, value2, "yakusyoku");
            return (Criteria) this;
        }

        public Criteria andMailIsNull() {
            addCriterion("MAIL is null");
            return (Criteria) this;
        }

        public Criteria andMailIsNotNull() {
            addCriterion("MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andMailEqualTo(String value) {
            addCriterion("MAIL =", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotEqualTo(String value) {
            addCriterion("MAIL <>", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThan(String value) {
            addCriterion("MAIL >", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL >=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThan(String value) {
            addCriterion("MAIL <", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThanOrEqualTo(String value) {
            addCriterion("MAIL <=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLike(String value) {
            addCriterion("MAIL like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotLike(String value) {
            addCriterion("MAIL not like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailIn(List<String> values) {
            addCriterion("MAIL in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotIn(List<String> values) {
            addCriterion("MAIL not in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailBetween(String value1, String value2) {
            addCriterion("MAIL between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotBetween(String value1, String value2) {
            addCriterion("MAIL not between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andJimuMailIsNull() {
            addCriterion("JIMU_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andJimuMailIsNotNull() {
            addCriterion("JIMU_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andJimuMailEqualTo(Integer value) {
            addCriterion("JIMU_MAIL =", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailNotEqualTo(Integer value) {
            addCriterion("JIMU_MAIL <>", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailGreaterThan(Integer value) {
            addCriterion("JIMU_MAIL >", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailGreaterThanOrEqualTo(Integer value) {
            addCriterion("JIMU_MAIL >=", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailLessThan(Integer value) {
            addCriterion("JIMU_MAIL <", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailLessThanOrEqualTo(Integer value) {
            addCriterion("JIMU_MAIL <=", value, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailIn(List<Integer> values) {
            addCriterion("JIMU_MAIL in", values, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailNotIn(List<Integer> values) {
            addCriterion("JIMU_MAIL not in", values, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailBetween(Integer value1, Integer value2) {
            addCriterion("JIMU_MAIL between", value1, value2, "jimuMail");
            return (Criteria) this;
        }

        public Criteria andJimuMailNotBetween(Integer value1, Integer value2) {
            addCriterion("JIMU_MAIL not between", value1, value2, "jimuMail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 26 11:49:01 KST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}