package com.example.thsmanager.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.thsmanager.entity.TorihikisakiMain;
import com.example.thsmanager.entity.TorihikisakiMainExample;

@Mapper
public interface TorihikisakiMainMapper {
	@Select("select * from torihikisaki_main")
	List<TorihikisakiMain> selectTorihikisakiMains();
	
	@Select("select * from torihikisaki_main where TORIHIKI_ID=#{torihikiId}")
	TorihikisakiMain selectTorihikisakiMain(Integer ID);
	
	@Insert("insert into torihikisaki_main(TORIHIKI_NAME_ALL, TORIHIKI_RYAKU, YUUBIN, JYUSYO_1, JYUSYO_2,"
	        + "TEL, FAX, URL, BIKOU, SEIKYUSYOU_KUBUN_1, SEIKYUSYOU_KUBUN_2, SEIKYUSYOU_KUBUN_3, SEIKYUSYOU_KUBUN_4, SEIKYUSYOU_KUBUN_5,"
	        + "SEIKYUSYOU_KUBUN_6, HONSYA, HONSYA_KOUZA, KINYUKIKAN_CODE, KINYUKIKAN_NAME, SITEN_CODE,"
	        + "SITEN_NAME, KOUZA_KIND, KOUZA_NUM, MEIGI_NAME)"
	        + "values(#{torihikiNameAll}, #{torihikiRyaku}, #{yuubin}, #{jyusyo1}, #{jyusyo2}, #{tel}, #{fax}"
	        + ", #{url}, #{bikou}, #{seikyusyouKubun1}, #{seikyusyouKubun2}, #{seikyusyouKubun3}, #{seikyusyouKubun4}, #{seikyusyouKubun5},"
	        + "#{seikyusyouKubun6}, #{honsya}, #{honsyaKouza}, #{kinyukikanCode}, #{kinyukikanName}, #{sitenCode}"
	        + ", #{sitenName}, #{kouzaKind}, #{kouzaNum}, #{meigiName})")
	void addTorihikisakiMain(TorihikisakiMain torihikisakiMain);

	
	@Update("update torihikisaki_main set TORIHIKI_NAME_ALL=#{torihikiNameALL},"
			+ "TORIHIKI_RYAKU=#{torihikiRyaku},YUUBIN=#{yuubin},JYUSYO_1=#{jyusyo1},JYUSYO_2=#{jyusyo2},"
			+ "TEL=#{tel},FAX=#{fax},URL=#{url},BIKOU=#{bikou},SEIKYUSYOU_KUBUN_1=#{seikyusyouKubun1},"
			+ "SEIKYUSYOU_KUBUN_2=#{seikyusyouKubun2},SEIKYUSYOU_KUBUN_3=#{seikyusyouKubun3},SEIKYUSYOU_KUBUN_4=#{seikyusyouKubun4},"
			+ "SEIKYUSYOU_KUBUN_5=#{seikyusyouKubun5},"
			+ "SEIKYUSYOU_KUBUN_6=#{seikyusyouKubun6},SEIKYUSYOU_KUBUN_7=#{seikyusyouKubun7},SEIKYUSYOU_KUBUN_8=#{seikyusyouKubun8},SEIKYUSYOU_KUBUN_9=#{seikyusyouKubun9},"
			+ "SEIKYUSYOU_KUBUN_10=#{seikyusyouKubun10},SEIKYUSYOU_KUBUN_11=#{seikyusyouKubun11},HONSYA=#{honsya},HONSYA_KOUZA=#{honsyaKouza},"
			+ "KINYUKIKAN_CODE=#{kinyukikanCode},KINYUKIKAN_NAME=#{kinyukikanName},SITEN_CODE=#{sitenCode},SITEN_NAME=#{sitenName},"
			+ "KOUZA_KIND=#{kouzaKind},KOUZA_NUM=#{kouzaNum},MEIGI_NAME=#{meigiName},KOUSINBI=#{kousinbi}")
	void updateTorihikisakiMain(TorihikisakiMain torihikisakiMain);
	
	@Delete("delete from torihikisaki_main where TORIHIKI_ID=#{torihikiId}")
	void delTorihikisakiMain(Integer torihikiId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    long countByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int deleteByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int deleteByPrimaryKey(Integer torihikiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int insert(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int insertSelective(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    List<TorihikisakiMain> selectByExample(TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    TorihikisakiMain selectByPrimaryKey(Integer torihikiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int updateByExampleSelective(@Param("row") TorihikisakiMain row, @Param("example") TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int updateByExample(@Param("row") TorihikisakiMain row, @Param("example") TorihikisakiMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int updateByPrimaryKeySelective(TorihikisakiMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_main
     *
     * @mbg.generated Sun Dec 24 12:48:52 KST 2023
     */
    int updateByPrimaryKey(TorihikisakiMain row);
}