package com.example.thsmanager.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.example.thsmanager.entity.TorihikisakiTantou;
import com.example.thsmanager.entity.TorihikisakiTantouExample;

@Mapper
public interface TorihikisakiTantouMapper {
	@Select("select * from torihikisaki_tantou")
	List<TorihikisakiTantou> selectTorihikisakiTantous();
	
	@Select("select * from torihikisaki_tantou where TANTOU_ID=#{tantouId}")
	TorihikisakiTantou selectTorihikisakiTantou(Integer tantouId);
	
	@Insert("insert into TORIHIKISAKI_TANTOU(TANTOU_ID, TORIHIKI_ID, FIRST_NAME, LAST_NAME, SYOZOKU, YAKUSYOKU, MAIL, TEL, JIMU_MAIL)"
	        + "values(#{tantouId}, #{torihikiId}, #{firstName}, #{lastName}, #{syoZoku}, #{yakusyoku}, #{mail}, #{tel}, #{jimuMail})")
	void addTorihikisakiTantou(TorihikisakiTantou torihikisakiTantou);

	
	@Update("update TORIHIKISAKI_TANTOU set "
		    + "FIRST_NAME=#{firstName}, LAST_NAME=#{lastName}, "
		    + "SYOZOKU=#{syoZoku}, YAKUSYOKU=#{yakusyoku}, "
		    + "MAIL=#{mail}, TEL=#{tel}, JIMU_MAIL=#{jimuMail} "
		    + "where TANTOU_ID=#{tantouId}")
	void updateTorihikisakiTantou(TorihikisakiTantou torihikisakiTantou);
	
	@Delete("delete from TORIHIKISAKI_TANTOU where TANTOU_ID=#{tantouId}")
	void delTorihikisakiTantou(Integer tantouId);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    long countByExample(TorihikisakiTantouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int deleteByExample(TorihikisakiTantouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int deleteByPrimaryKey(Integer tantouId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int insert(TorihikisakiTantou row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int insertSelective(TorihikisakiTantou row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    List<TorihikisakiTantou> selectByExample(TorihikisakiTantouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    TorihikisakiTantou selectByPrimaryKey(Integer tantouId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int updateByExampleSelective(@Param("row") TorihikisakiTantou row, @Param("example") TorihikisakiTantouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int updateByExample(@Param("row") TorihikisakiTantou row, @Param("example") TorihikisakiTantouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int updateByPrimaryKeySelective(TorihikisakiTantou row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table torihikisaki_tantou
     *
     * @mbg.generated Tue Dec 26 11:49:01 KST 2023
     */
    int updateByPrimaryKey(TorihikisakiTantou row);
}